esphome:
  name: vrf-01s
  friendly_name: vrf-01s
  name_add_mac_suffix: true

external_components:
  - source:
      type: git
      url: https://github.com/idreamshen/esphome-uart-vrf

uart:
  - id: myuart1
    tx_pin: 1
    rx_pin: 3
    baud_rate: 9600


uart_vrf:
  allow_heat_mode_sensor: allow_heat_mode_sensor

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

api:
  encryption:
    key: "vUAZJVUjuhi2kEiYRjjAwsSxuXVvUd1PTPNJWGNa2rs="

ota:
  - platform: esphome

wifi:
  ap:
    password: "12345678"

captive_portal:

web_server:
  port: 80
  local: true

switch:
  - platform: restart
    name: "重启设备 Reboot"
    id: switch_reboot
  - platform: factory_reset
    name: "恢复出厂配置 Reset"
    id: switch_reset
  - platform: template
    name: "允许制热模式 Allow Heat"
    id: allow_heat_mode_control
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
  - platform: template
    internal: True
    name: "Allow Heat Mode Sensor"
    id: allow_heat_mode_sensor
    lambda: |-
      return id(allow_heat_mode_control).state;
