esphome:
  name: vrf-32wroom32d
  friendly_name: vrf-32wroom32d
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
    advanced:
      ignore_efuse_custom_mac: true
      ignore_efuse_mac_crc: true

external_components:
  - source:
      type: git
      url: https://github.com/idreamshen/esphome-uart-vrf

logger:

api:
  encryption:
    key: "vUAZJVUjuhi2kEiYRjjAwsSxuXVvUd1PTPNJWGNa2rs="

ota:
  - platform: esphome
    password: "161fdd9fedb5649b758a44978e20caf8"

wifi:
  ap:
    password: "12345678"

captive_portal:

uart:
  - id: myuart1
    tx_pin: 17
    rx_pin: 16
    baud_rate: 9600
    debug:
      direction: RX
      dummy_receiver: false
      sequence:
        - light.turn_on: receive_led
        - delay: 200ms
        - light.turn_off: receive_led

output:
  - platform: gpio
    pin:
      number: 15
      inverted: true
    id: led_output

light:
  - platform: binary
    name: "RX LED"
    output: led_output
    id: receive_led
    internal: true

uart_vrf:
  allow_heat_mode_sensor: allow_heat_mode_sensor

web_server:
  port: 80
  local: true

switch:
  - platform: restart
    name: "重启设备 Reboot"
    id: switch_reboot
  - platform: factory_reset
    name: "恢复出厂配置 Reset"
    id: switch_reset
  - platform: template
    name: "允许制热模式 Allow Heat"
    id: allow_heat_mode_control
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

binary_sensor:
  - platform: template
    internal: True
    name: "Allow Heat Mode Sensor"
    id: allow_heat_mode_sensor
    lambda: |-
      return id(allow_heat_mode_control).state;
